SELECT user_id,
  menor18,
  entre18y24,
  entre25y29,
  entre30y34,
  entre35y39,
  entre40y49,
  mayor50,
  edad_desconocida,
  femenino,
  masculino,
  genero_desconocido,
  item_id,
  cat_id,
  merchant_id,
  brand_id,
  time_stamp,
  click,
  carro,
  comprar,
  favorito,
  accion_desconocida,
  no_repetido,
  repetido,
  tipo_desconocido
FROM dummie_join_table TABLESAMPLE(BUCKET 1 OUT OF 1000 ON rand()) as rs
where rs.repetido = 1
union
SELECT user_id,
  menor18,
  entre18y24,
  entre25y29,
  entre30y34,
  entre35y39,
  entre40y49,
  mayor50,
  edad_desconocida,
  femenino,
  masculino,
  genero_desconocido,
  item_id,
  cat_id,
  merchant_id,
  brand_id,
  time_stamp,
  click,
  carro,
  comprar,
  favorito,
  accion_desconocida,
  no_repetido,
  repetido,
  tipo_desconocido
FROM dummie_join_table TABLESAMPLE(BUCKET 1 OUT OF 1000 ON rand()) as s
where s.no_repetido = 1;
